name: mountalgo_terminal
description: High-performance mobile trading terminal - MountAlgo Terminal official app.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.17.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
